package net.socialhub.define;

import java.util.stream.Stream;

public enum EmojiCategoryType {

    // Auto Generated Code
    // see EmojiGenerator.java (Test)

    //region // AutoGenerated Code

    Symbols("Symbols"),
    Activities("Activities"),
    Flags("Flags"),
    TravelPlaces("Travel & Places"),
    FoodDrink("Food & Drink"),
    AnimalsNature("Animals & Nature"),
    SmileysPeople("Smileys & People"),
    Objects("Objects"),
    SkinTones("Skin Tones"),

    //endregion

    /** custom emoji */
    Custom("Custom"),

    ;

    private String code;

    EmojiCategoryType(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }

    public static EmojiCategoryType of(String code) {
        return Stream.of(values()) //
                .filter(e -> e.getCode().equals(code)) //
                .findFirst().orElse(null);
    }
}
